// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs_VieyBd9Y5_H7LbPx93_zaqJR7sfOY4',
    appId: '1:1019288057828:web:3ce10f6ce93457dcf4b9f1',
    messagingSenderId: '1019288057828',
    projectId: 'snapmap-5050d',
    authDomain: 'snapmap-5050d.firebaseapp.com',
    storageBucket: 'snapmap-5050d.firebasestorage.app',
    measurementId: 'G-GS07D678SD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYJcQ3UunWbU5qCR3wilwA0Kpv_IunLsE',
    appId: '1:1019288057828:android:9dc7c09eddd83571f4b9f1',
    messagingSenderId: '1019288057828',
    projectId: 'snapmap-5050d',
    storageBucket: 'snapmap-5050d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn6_3o_b6ulzcckeYWT-8UzPimyDtobNQ',
    appId: '1:1019288057828:ios:5707fdb305a47fb1f4b9f1',
    messagingSenderId: '1019288057828',
    projectId: 'snapmap-5050d',
    storageBucket: 'snapmap-5050d.firebasestorage.app',
    iosClientId:
        '1019288057828-grmtccahmj2o8bhc3114di523ehg7rhm.apps.googleusercontent.com',
    iosBundleId: 'com.example.snapmap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn6_3o_b6ulzcckeYWT-8UzPimyDtobNQ',
    appId: '1:1019288057828:ios:5707fdb305a47fb1f4b9f1',
    messagingSenderId: '1019288057828',
    projectId: 'snapmap-5050d',
    storageBucket: 'snapmap-5050d.firebasestorage.app',
    iosClientId:
        '1019288057828-grmtccahmj2o8bhc3114di523ehg7rhm.apps.googleusercontent.com',
    iosBundleId: 'com.example.snapmap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs_VieyBd9Y5_H7LbPx93_zaqJR7sfOY4',
    appId: '1:1019288057828:web:f85f973d3bf056cff4b9f1',
    messagingSenderId: '1019288057828',
    projectId: 'snapmap-5050d',
    authDomain: 'snapmap-5050d.firebaseapp.com',
    storageBucket: 'snapmap-5050d.firebasestorage.app',
    measurementId: 'G-SSWBSTF8YZ',
  );
}
